gg_snd_PursuitTheme = ""
function InitGlobals()
end

function InitSounds()
gg_snd_PursuitTheme = "PursuitTheme"
end

function CreateBuildingsForPlayer9()
local p = Player(9)
local u
local unitID
local t
local life

u = BlzCreateUnitWithSkin(p, FourCC("h003"), 0.0, 0.0, 270.000, FourCC("h003"))
u = BlzCreateUnitWithSkin(p, FourCC("hgtw"), -1728.0, 192.0, 270.000, FourCC("hgtw"))
u = BlzCreateUnitWithSkin(p, FourCC("hgtw"), -1152.0, -1344.0, 270.000, FourCC("hgtw"))
u = BlzCreateUnitWithSkin(p, FourCC("hgtw"), 1408.0, 1344.0, 270.000, FourCC("hgtw"))
u = BlzCreateUnitWithSkin(p, FourCC("hgtw"), 1792.0, 832.0, 270.000, FourCC("hgtw"))
u = BlzCreateUnitWithSkin(p, FourCC("hgtw"), 1920.0, -640.0, 270.000, FourCC("hgtw"))
u = BlzCreateUnitWithSkin(p, FourCC("hgtw"), 1792.0, -1344.0, 270.000, FourCC("hgtw"))
u = BlzCreateUnitWithSkin(p, FourCC("hhou"), -1728.0, -5632.0, 270.000, FourCC("hhou"))
u = BlzCreateUnitWithSkin(p, FourCC("hhou"), -1600.0, -5504.0, 270.000, FourCC("hhou"))
u = BlzCreateUnitWithSkin(p, FourCC("h004"), -1408.0, -6528.0, 270.000, FourCC("h004"))
u = BlzCreateUnitWithSkin(p, FourCC("hgtw"), -448.0, -6272.0, 270.000, FourCC("hgtw"))
u = BlzCreateUnitWithSkin(p, FourCC("h004"), -7744.0, -1344.0, 270.000, FourCC("h004"))
u = BlzCreateUnitWithSkin(p, FourCC("h004"), -5056.0, 7808.0, 270.000, FourCC("h004"))
u = BlzCreateUnitWithSkin(p, FourCC("h004"), 6976.0, 5376.0, 270.000, FourCC("h004"))
u = BlzCreateUnitWithSkin(p, FourCC("h004"), 10304.0, -1024.0, 270.000, FourCC("h004"))
u = BlzCreateUnitWithSkin(p, FourCC("h004"), 7424.0, -9344.0, 270.000, FourCC("h004"))
u = BlzCreateUnitWithSkin(p, FourCC("h004"), -1920.0, -12736.0, 270.000, FourCC("h004"))
u = BlzCreateUnitWithSkin(p, FourCC("hhou"), 128.0, -12544.0, 270.000, FourCC("hhou"))
u = BlzCreateUnitWithSkin(p, FourCC("hhou"), 320.0, -12480.0, 270.000, FourCC("hhou"))
end

function CreateUnitsForPlayer9()
local p = Player(9)
local u
local unitID
local t
local life

u = BlzCreateUnitWithSkin(p, FourCC("hrif"), -6385.8, -1009.6, 21.435, FourCC("hrif"))
u = BlzCreateUnitWithSkin(p, FourCC("nmed"), 919.3, -2424.1, 175.798, FourCC("nmed"))
u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), 2084.0, -632.7, 312.724, FourCC("hfoo"))
u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), 2035.0, -721.6, 327.998, FourCC("hfoo"))
u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), 1927.7, -1256.7, 343.692, FourCC("hfoo"))
u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), 1926.8, -1380.8, 13.231, FourCC("hfoo"))
u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), 1492.6, 1550.1, 32.324, FourCC("hfoo"))
u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), 1544.3, 1475.5, 40.407, FourCC("hfoo"))
u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), 1889.0, 1013.1, 45.671, FourCC("hfoo"))
u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), 1990.3, 961.6, 51.651, FourCC("hfoo"))
u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), -2014.7, 223.5, 196.822, FourCC("hfoo"))
u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), -2011.9, 89.7, 183.951, FourCC("hfoo"))
u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), -1389.3, -1334.4, 212.634, FourCC("hfoo"))
u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), -1306.3, -1466.5, 204.344, FourCC("hfoo"))
u = BlzCreateUnitWithSkin(p, FourCC("nhef"), -1510.2, -5595.5, 252.108, FourCC("nhef"))
u = BlzCreateUnitWithSkin(p, FourCC("nhem"), -1634.4, -5710.8, 47.183, FourCC("nhem"))
u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), -1554.4, -6880.9, -78.580, FourCC("hfoo"))
u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), -421.1, -6391.3, -14.449, FourCC("hfoo"))
u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), -1851.5, -5769.4, 213.009, FourCC("hfoo"))
u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), -1700.6, -6721.2, 222.014, FourCC("hfoo"))
u = BlzCreateUnitWithSkin(p, FourCC("hrif"), -1871.1, 204.2, 226.295, FourCC("hrif"))
u = BlzCreateUnitWithSkin(p, FourCC("hrif"), -1287.0, -1240.9, 261.549, FourCC("hrif"))
u = BlzCreateUnitWithSkin(p, FourCC("hrif"), 1861.0, -757.6, -34.153, FourCC("hrif"))
u = BlzCreateUnitWithSkin(p, FourCC("hrif"), 1799.1, -1181.6, 307.165, FourCC("hrif"))
u = BlzCreateUnitWithSkin(p, FourCC("hrif"), 1518.8, 1315.8, 7.697, FourCC("hrif"))
u = BlzCreateUnitWithSkin(p, FourCC("hrif"), 1750.5, 1036.7, 48.081, FourCC("hrif"))
u = BlzCreateUnitWithSkin(p, FourCC("hkni"), -229.6, -247.7, 256.495, FourCC("hkni"))
u = BlzCreateUnitWithSkin(p, FourCC("hkni"), 253.4, -242.8, -59.913, FourCC("hkni"))
u = BlzCreateUnitWithSkin(p, FourCC("hspt"), -76.0, -294.2, 244.587, FourCC("hspt"))
u = BlzCreateUnitWithSkin(p, FourCC("hspt"), 122.1, -274.7, -73.195, FourCC("hspt"))
u = BlzCreateUnitWithSkin(p, FourCC("Hpal"), 26.5, -328.0, 278.370, FourCC("Hpal"))
SetHeroLevel(u, 10, false)
SelectHeroSkill(u, FourCC("AHhb"))
SelectHeroSkill(u, FourCC("AHhb"))
SelectHeroSkill(u, FourCC("AHhb"))
SelectHeroSkill(u, FourCC("AHds"))
SelectHeroSkill(u, FourCC("AHds"))
SelectHeroSkill(u, FourCC("AHds"))
SelectHeroSkill(u, FourCC("AHad"))
SelectHeroSkill(u, FourCC("AHad"))
SelectHeroSkill(u, FourCC("AHad"))
SelectHeroSkill(u, FourCC("AHre"))
UnitAddItemToSlotById(u, FourCC("ofro"), 0)
UnitAddItemToSlotById(u, FourCC("ward"), 1)
u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), -2146.4, -12980.2, 216.599, FourCC("hfoo"))
u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), -1826.8, -12998.8, -23.267, FourCC("hfoo"))
u = BlzCreateUnitWithSkin(p, FourCC("hkni"), -1980.3, -13057.1, 267.767, FourCC("hkni"))
u = BlzCreateUnitWithSkin(p, FourCC("hrif"), -6481.4, -978.1, 184.895, FourCC("hrif"))
u = BlzCreateUnitWithSkin(p, FourCC("hkni"), -7799.3, -269.9, 318.624, FourCC("hkni"))
u = BlzCreateUnitWithSkin(p, FourCC("hmpr"), -7685.8, -269.3, 140.366, FourCC("hmpr"))
u = BlzCreateUnitWithSkin(p, FourCC("hrif"), -8838.7, -1255.3, -9.105, FourCC("hrif"))
u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), -8853.4, -1041.0, -24.227, FourCC("hfoo"))
u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), -8788.3, -854.2, -37.748, FourCC("hfoo"))
u = BlzCreateUnitWithSkin(p, FourCC("hmpr"), -7158.0, -2295.5, 135.213, FourCC("hmpr"))
u = BlzCreateUnitWithSkin(p, FourCC("hmpr"), -7659.0, -2459.4, 31.510, FourCC("hmpr"))
u = BlzCreateUnitWithSkin(p, FourCC("nhea"), -7518.6, -2497.1, 18.304, FourCC("nhea"))
u = BlzCreateUnitWithSkin(p, FourCC("nhea"), -7283.6, -2462.5, 119.981, FourCC("nhea"))
u = BlzCreateUnitWithSkin(p, FourCC("nhef"), -7777.2, -2429.8, 43.760, FourCC("nhef"))
u = BlzCreateUnitWithSkin(p, FourCC("nhef"), -7907.1, -2415.1, 132.840, FourCC("nhef"))
u = BlzCreateUnitWithSkin(p, FourCC("nhef"), -7559.9, -288.2, 306.330, FourCC("nhef"))
u = BlzCreateUnitWithSkin(p, FourCC("nhef"), -6589.1, -702.5, 71.919, FourCC("nhef"))
u = BlzCreateUnitWithSkin(p, FourCC("nemi"), -6712.3, -590.2, 265.433, FourCC("nemi"))
end

function CreateNeutralPassiveBuildings()
local p = Player(PLAYER_NEUTRAL_PASSIVE)
local u
local unitID
local t
local life

u = BlzCreateUnitWithSkin(p, FourCC("n001"), -16000.0, -15680.0, 270.000, FourCC("n001"))
SetUnitColor(u, ConvertPlayerColor(0))
u = BlzCreateUnitWithSkin(p, FourCC("n002"), -576.0, 1024.0, 270.000, FourCC("n002"))
u = BlzCreateUnitWithSkin(p, FourCC("n003"), 16192.0, -16448.0, 270.000, FourCC("n003"))
SetUnitColor(u, ConvertPlayerColor(0))
end

function CreateNeutralPassive()
local p = Player(PLAYER_NEUTRAL_PASSIVE)
local u
local unitID
local t
local life

u = BlzCreateUnitWithSkin(p, FourCC("ncco"), -1069.8, -6479.6, -54.060, FourCC("ncco"))
u = BlzCreateUnitWithSkin(p, FourCC("nccd"), -950.8, -6278.4, -56.168, FourCC("nccd"))
u = BlzCreateUnitWithSkin(p, FourCC("nccr"), -778.8, -6426.3, 288.927, FourCC("nccr"))
u = BlzCreateUnitWithSkin(p, FourCC("nccu"), -697.2, -6182.1, -86.577, FourCC("nccu"))
end

function CreatePlayerBuildings()
CreateBuildingsForPlayer9()
end

function CreatePlayerUnits()
CreateUnitsForPlayer9()
end

function CreateAllUnits()
CreateNeutralPassiveBuildings()
CreatePlayerBuildings()
CreateNeutralPassive()
CreatePlayerUnits()
end

function InitCustomPlayerSlots()
SetPlayerStartLocation(Player(0), 0)
ForcePlayerStartLocation(Player(0), 0)
SetPlayerColor(Player(0), ConvertPlayerColor(0))
SetPlayerRacePreference(Player(0), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(0), false)
SetPlayerController(Player(0), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(1), 1)
ForcePlayerStartLocation(Player(1), 1)
SetPlayerColor(Player(1), ConvertPlayerColor(1))
SetPlayerRacePreference(Player(1), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(1), false)
SetPlayerController(Player(1), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(2), 2)
ForcePlayerStartLocation(Player(2), 2)
SetPlayerColor(Player(2), ConvertPlayerColor(2))
SetPlayerRacePreference(Player(2), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(2), false)
SetPlayerController(Player(2), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(3), 3)
ForcePlayerStartLocation(Player(3), 3)
SetPlayerColor(Player(3), ConvertPlayerColor(3))
SetPlayerRacePreference(Player(3), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(3), false)
SetPlayerController(Player(3), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(4), 4)
ForcePlayerStartLocation(Player(4), 4)
SetPlayerColor(Player(4), ConvertPlayerColor(4))
SetPlayerRacePreference(Player(4), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(4), false)
SetPlayerController(Player(4), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(5), 5)
ForcePlayerStartLocation(Player(5), 5)
SetPlayerColor(Player(5), ConvertPlayerColor(5))
SetPlayerRacePreference(Player(5), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(5), false)
SetPlayerController(Player(5), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(6), 6)
ForcePlayerStartLocation(Player(6), 6)
SetPlayerColor(Player(6), ConvertPlayerColor(6))
SetPlayerRacePreference(Player(6), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(6), false)
SetPlayerController(Player(6), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(7), 7)
ForcePlayerStartLocation(Player(7), 7)
SetPlayerColor(Player(7), ConvertPlayerColor(7))
SetPlayerRacePreference(Player(7), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(7), false)
SetPlayerController(Player(7), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(8), 8)
ForcePlayerStartLocation(Player(8), 8)
SetPlayerColor(Player(8), ConvertPlayerColor(8))
SetPlayerRacePreference(Player(8), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(8), false)
SetPlayerController(Player(8), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(9), 9)
ForcePlayerStartLocation(Player(9), 9)
SetPlayerColor(Player(9), ConvertPlayerColor(9))
SetPlayerRacePreference(Player(9), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(9), false)
SetPlayerController(Player(9), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(10), 10)
ForcePlayerStartLocation(Player(10), 10)
SetPlayerColor(Player(10), ConvertPlayerColor(10))
SetPlayerRacePreference(Player(10), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(10), false)
SetPlayerController(Player(10), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(11), 11)
ForcePlayerStartLocation(Player(11), 11)
SetPlayerColor(Player(11), ConvertPlayerColor(11))
SetPlayerRacePreference(Player(11), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(11), false)
SetPlayerController(Player(11), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(16), 12)
SetPlayerColor(Player(16), ConvertPlayerColor(16))
SetPlayerRacePreference(Player(16), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(16), false)
SetPlayerController(Player(16), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(20), 13)
SetPlayerColor(Player(20), ConvertPlayerColor(20))
SetPlayerRacePreference(Player(20), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(20), false)
SetPlayerController(Player(20), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(21), 14)
SetPlayerColor(Player(21), ConvertPlayerColor(21))
SetPlayerRacePreference(Player(21), RACE_PREF_ORC)
SetPlayerRaceSelectable(Player(21), false)
SetPlayerController(Player(21), MAP_CONTROL_COMPUTER)
end

function InitCustomTeams()
SetPlayerTeam(Player(0), 0)
SetPlayerState(Player(0), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(1), 0)
SetPlayerState(Player(1), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(2), 0)
SetPlayerState(Player(2), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(3), 0)
SetPlayerState(Player(3), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(4), 0)
SetPlayerState(Player(4), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(5), 0)
SetPlayerState(Player(5), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(9), 0)
SetPlayerState(Player(9), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerAllianceStateAllyBJ(Player(0), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(5), true)
SetPlayerTeam(Player(6), 1)
SetPlayerState(Player(6), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(7), 1)
SetPlayerState(Player(7), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(8), 1)
SetPlayerState(Player(8), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(10), 1)
SetPlayerState(Player(10), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(11), 1)
SetPlayerState(Player(11), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(16), 1)
SetPlayerState(Player(16), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(20), 1)
SetPlayerState(Player(20), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerAllianceStateAllyBJ(Player(6), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(6), Player(7), true)
SetPlayerAllianceStateVisionBJ(Player(6), Player(8), true)
SetPlayerAllianceStateVisionBJ(Player(6), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(6), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(6), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(6), Player(20), true)
SetPlayerAllianceStateVisionBJ(Player(7), Player(6), true)
SetPlayerAllianceStateVisionBJ(Player(7), Player(8), true)
SetPlayerAllianceStateVisionBJ(Player(7), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(7), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(7), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(7), Player(20), true)
SetPlayerAllianceStateVisionBJ(Player(8), Player(6), true)
SetPlayerAllianceStateVisionBJ(Player(8), Player(7), true)
SetPlayerAllianceStateVisionBJ(Player(8), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(8), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(8), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(8), Player(20), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(6), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(7), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(8), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(20), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(6), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(7), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(8), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(20), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(6), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(7), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(8), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(20), true)
SetPlayerAllianceStateVisionBJ(Player(20), Player(6), true)
SetPlayerAllianceStateVisionBJ(Player(20), Player(7), true)
SetPlayerAllianceStateVisionBJ(Player(20), Player(8), true)
SetPlayerAllianceStateVisionBJ(Player(20), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(20), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(20), Player(16), true)
SetPlayerTeam(Player(21), 2)
SetPlayerState(Player(21), PLAYER_STATE_ALLIED_VICTORY, 1)
end

function InitAllyPriorities()
SetStartLocPrioCount(0, 5)
SetStartLocPrio(0, 0, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(0, 1, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(0, 2, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(0, 3, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(0, 4, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(1, 5)
SetStartLocPrio(1, 0, 0, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(1, 1, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(1, 2, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(1, 3, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(1, 4, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(2, 5)
SetStartLocPrio(2, 0, 0, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(2, 1, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(2, 2, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(2, 3, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(2, 4, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(3, 5)
SetStartLocPrio(3, 0, 0, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(3, 1, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(3, 2, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(3, 3, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(3, 4, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(4, 5)
SetStartLocPrio(4, 0, 0, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(4, 1, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(4, 2, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(4, 3, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(4, 4, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(5, 5)
SetStartLocPrio(5, 0, 0, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(5, 1, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(5, 2, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(5, 3, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(5, 4, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(6, 2)
SetStartLocPrio(6, 0, 7, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(6, 1, 13, MAP_LOC_PRIO_LOW)
SetStartLocPrioCount(7, 2)
SetStartLocPrio(7, 0, 10, MAP_LOC_PRIO_LOW)
SetStartLocPrio(7, 1, 13, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(8, 1)
SetStartLocPrio(8, 0, 11, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(9, 12)
SetStartLocPrio(9, 0, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(9, 1, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(9, 2, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(9, 3, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(9, 4, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(9, 5, 6, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(9, 6, 7, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(9, 7, 8, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(9, 8, 10, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(9, 9, 11, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(9, 10, 12, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(9, 11, 13, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(10, 2)
SetStartLocPrio(10, 0, 7, MAP_LOC_PRIO_LOW)
SetStartLocPrio(10, 1, 13, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(11, 1)
SetStartLocPrio(11, 0, 8, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(12, 12)
SetStartLocPrio(12, 0, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(12, 1, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(12, 2, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(12, 3, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(12, 4, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(12, 5, 6, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(12, 6, 7, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(12, 7, 8, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(12, 8, 9, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(12, 9, 10, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(12, 10, 11, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(12, 11, 13, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(13, 2)
SetStartLocPrio(13, 0, 7, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(13, 1, 10, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(14, 3)
SetStartLocPrio(14, 0, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(14, 1, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(14, 2, 6, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrioCount(14, 6)
SetEnemyStartLocPrio(14, 0, 4, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(14, 1, 5, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(14, 2, 6, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(14, 3, 10, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(14, 4, 13, MAP_LOC_PRIO_HIGH)
end

function main()
SetCameraBounds(-17664.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), -17920.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 17664.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 17408.0 - GetCameraMargin(CAMERA_MARGIN_TOP), -17664.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 17408.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 17664.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), -17920.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM))
SetDayNightModels("Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl", "Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl")
NewSoundEnvironment("Default")
SetAmbientDaySound("LordaeronSummerDay")
SetAmbientNightSound("LordaeronSummerNight")
SetMapMusic("Music", true, 0)
InitSounds()
CreateAllUnits()
InitBlizzard()
InitGlobals()
end

function config()
SetMapName("TRIGSTR_003")
SetMapDescription("TRIGSTR_005")
SetPlayers(15)
SetTeams(15)
SetGamePlacement(MAP_PLACEMENT_TEAMS_TOGETHER)
DefineStartLocation(0, -15616.0, -16064.0)
DefineStartLocation(1, -15616.0, -16064.0)
DefineStartLocation(2, -15616.0, -16064.0)
DefineStartLocation(3, -15616.0, -16064.0)
DefineStartLocation(4, -15616.0, -16064.0)
DefineStartLocation(5, -15616.0, -16064.0)
DefineStartLocation(6, 2560.0, 6144.0)
DefineStartLocation(7, 3328.0, 1152.0)
DefineStartLocation(8, -3712.0, 1216.0)
DefineStartLocation(9, -5120.0, -13632.0)
DefineStartLocation(10, 4672.0, -2176.0)
DefineStartLocation(11, -4480.0, 896.0)
DefineStartLocation(12, -3968.0, 4928.0)
DefineStartLocation(13, 2368.0, -1408.0)
DefineStartLocation(14, -3584.0, 5824.0)
InitCustomPlayerSlots()
InitCustomTeams()
InitAllyPriorities()
end

